trigger:
  tags:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

stages:
  - stage:
    displayName: Release
    jobs:
      - job: 
        displayName: Release to GitHub
        steps:
          - task: ArchiveFiles@2
            displayName: Create archive from theme folder
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/theme'
              includeRootFolder: false
              archiveType: tar
              tarCompression: none
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.SourceBranchName).tar'
              
          - task: GithubRelease@1 
            displayName: 'Create GitHub Release'
            inputs:
              gitHubConnection: github
              repositoryName: johnnyhansson/keycloak.theme
              tagSource: gitTag
              assets: |
                $(Build.ArtifactStagingDirectory)/$(Build.SourceBranchName).tar